services:
  - type: web
    name: picha-backend
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader vader_lexicon
    # startCommand yazmırıq, çünki Procfile istifadə olunur
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
